; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.16"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ff][download][type] = ""
projects[ff][download][url] = ""
projects[ff][type] = "profile"

; Modules
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta3"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.4"

projects[commerce_features][subdir] = "contrib"
projects[commerce_features][version] = "1.0-rc1"

projects[commerce_paypal][subdir] = "contrib"
projects[commerce_paypal][version] = "1.0-rc1"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc3"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[geocoder][subdir] = "contrib"
projects[geocoder][version] = "1.2"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "1.1"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "1.0"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.5"

projects[epay][type] = "module"
projects[epay][download][type] = "git"
projects[epay][download][url] = "http://git.drupal.org/project/epay.git"
projects[epay][download][revision] = "d68bd9814c5daa8cba5d035ab9da3c5a377e55b5"

projects[services][subdir] = "contrib"
projects[services][version] = "3.3"
