<?php
/**
 * @file
 * ffr_purchase.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function ffr_purchase_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ffr_blabla';
  $strongarm->value = 1;
  $export['ffr_blabla'] = $strongarm;

  return $export;
}
